
token: uQ5RHimaxAEgWnZG

server:
  tomcat:
    uri-encoding: UTF-8
  port: 8181


spring:
  mvc:
    view:
      prefix: /
      suffix: .html
  resources:
    static-locations: classpath:static/
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
    multipart:
      enabled: true
      max-file-size: -1


file-manager:
     thumbnail:
        width: 80 # 缩略图宽
     volumes:
        - Node:
          appkey: files1
          source: fileSystem # 暂时只支持本地文件系统
          alias: Files # 目录别名
          path: /Users/twinkle/git/elfinder1 # 映射目录   D:/elfinder
          host: http://localhost:8899 #与映射目录下的相对路径拼接，host可以设置为相对地址，如/download
          _default: true # 是否默认打开
          locale:
          constraint:
            locked: false # 文件夹是否锁定
            readable: true # 是否可读
            writable: true # 是否可写
        - Node:
          appkey: files2
          source: fileSystem # 暂时只支持本地文件系统
          alias: Files2 # 目录别名
          path: /Users/twinkle/git/elfinder2 # 映射目录   /D:/elfinder
          host: http://localhost:8898 #与映射目录下的相对路径拼接，host可以设置为相对地址，如/download
          _default: true # 是否默认打开
          locale:
          constraint:
            locked: false # 文件夹是否锁定
            readable: true # 是否可读
            writable: true # 是否可写










